description: RL4Con Data Generation

target:
  service: sing
  name: msrresrchvc
  vc: gcr-singularity-resrch
  # service: amlk8s
  # name: ms-shared
  # vc: MS-Shared
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  # name: msrresrchvc
  # vc: gcr-singularity-resrch

environment:
  image: smpl:v1
  registry: resrchvc4cr.azurecr.io # any public registry can be specified here
  username: resrchvc4cr
  setup:
    - apt-get update
    - pip install casadi
    - pip install mpctools
    - pip install -r requirements.txt
    

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

data:
  local_dir: $CONFIG_DIR/
  remote_dir: rl4con/v1/


jobs:

- name: rl4con-10000
  sku: G1
  command:
  - python data_collection.py --amlt --steps 10000

- name: rl4con-100000
  sku: G1
  command:
  - python data_collection.py --amlt --steps 100000


# - name: smpl_reactor_data_pid
#   sku: G1
#   command:
#   - python smpl-experiments/reactorenv_experiments/offline_data_generation.py --policy pid --amlt
