description: RL4Con Data Generation

target:
  service: sing
  name: msrresrchvc
  vc: gcr-singularity-resrch
  # service: amlk8s
  # name: ms-shared
  # vc: MS-Shared
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  # name: msrresrchvc
  # vc: gcr-singularity-resrch

environment:
  image: smpl:v1
  registry: resrchvc4cr.azurecr.io # any public registry can be specified here
  username: resrchvc4cr
  setup:
    - apt-get update
    - pip install casadi
    - pip install mpctools
    - pip install -r requirements.txt
    

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

data:
  local_dir: $CONFIG_DIR/
  remote_dir: rl4con/v1/


jobs:

- name: CSTR-data-0-1000
  sku: C2
  command:
  - python data_collection.py --amlt --start_episodes 0 --end_episodes 1000 --env CSTR --seed 3

- name: CSTR-data-1000-2000
  sku: C2
  command:
  - python data_collection.py --amlt --start_episodes 1000 --end_episodes 2000 --env CSTR --seed 5

- name: CSTR-data-2000-3000
  sku: C2
  command:
  - python data_collection.py --amlt --start_episodes 2000 --end_episodes 3000 --env CSTR --seed 7

- name: CSTR-data-3000-4000
  sku: C2
  command:
  - python data_collection.py --amlt --start_episodes 3000 --end_episodes 4000 --env CSTR --seed 11

- name: CSTR-data-4000-5000
  sku: C2
  command:
  - python data_collection.py --amlt --start_episodes 4000 --end_episodes 5000 --env CSTR --seed 17

- name: CSTR-data-5000-6000
  sku: C2
  command:
  - python data_collection.py --amlt --start_episodes 5000 --end_episodes 6000 --env CSTR --seed 19

- name: CSTR-data-6000-7000
  sku: C2
  command:
  - python data_collection.py --amlt --start_episodes 6000 --end_episodes 7000 --env CSTR --seed 23

- name: CSTR-data-7000-8000
  sku: C2
  command:
  - python data_collection.py --amlt --start_episodes 7000 --end_episodes 8000 --env CSTR --seed 29