model:
  - model_type: continuous/discrete
  - variables
    - variable1
      - type
      - definition (optional, in case of auxiliary/ variable)
  - differential equations
    - equation1
      - lhs: variable name
      - rhs: equation, e.g., mu_S*X_s - (u-V_s)*X_s
    - equation2  
      - lhs
      - rhs

simulator:
  parameters:
    - integration_tool: 'cvodes'
    - abstol: 1e-10
    - reltol: 1e-10
    - t_step: 1.0
    - total_steps: 50

  reward:
    - observation
      - distance to steady
        - norm
        - coefficiency
      - distance to previous
        - norm
        - coefficiency
      - customize
    - action
      - distance to steady
        - norm
        - coefficiency
      - distance to previous
        - norm
        - coefficiency
      - customize

  model_parameters:
    - state/control variable:
      - lower bound
      - upper bound
      - constraint type: soft/hard
      - penalty coefficient: in case of soft constraint
      - penalty calculator: optional, default L1/L2
      - init_value: optional
      - steady_value: optional
    - constant parameter: 
      - value 
    - time varying parameter:
      - sampler: f(time_step)
        - parameters
    - noisy parameter:
      - sampler
        - parameters
    
estimator:
  - estimator type: StateFeedback/EKF(Extended Kalman Filter)/MHE(Moving Horizon Estimation)
  - parameters:
    - estimator related paramaters

observation_scaler:
  - name
  - parameters


action_scaler:
  - name
  - parameters


reward_scaler:
  - name
  - parameters