# A template to be refined
# important packages: do-mpc, d3rlpy, smpl

model:
  - model_name: batch_reactor
  - model_type: continuous
  - constants:
    - mu_m: 0.02
    - K_m: 0.05
    - K_i: 5.0
    - v_par: 0.004
    - Y_p: 1.2

  - state_variables:
    - X_s: 
      - rhs: mu_S*X_s - inp/V_s*X_s
      - shape: (1,) # default value, can be omitted
    - S_s: 
      - rhs: mu_S*X_s/Y_x - v_par*X_s/Y_p + inp/V_s*(S_in-S_s)
    - P_s: 
      - rhs: v_par*X_s - inp/V_s*P_s
    - V_s:
      - rhs: inp

  - control_variables:
    - inp:
      - shape: (1,) # default value, can be omitted
  
  - user_defined_parameters:
    - Y_x
    - S_in
  - aux_variables:
    - mu_S: mu_m*S_s/(K_m+S_s+(S_s**2/K_i))


simulator:
  parameters:
    - integration_tool: 'cvodes'
    - abstol: 1e-10
    - reltol: 1e-10
    - t_step: 1.0
  
  total_steps: 50

  reward:
    - observation:
      - distance_to_steady:
        - norm: L1
        - coef: 0.1
      - distance_to_previous:
        - norm: L1
        - coef: 0.1
      - abs_val:
        - variable: P_s
        - coef: 0.1
    - action:
      - distance_to_steady:
        - norm: L1
        - coef: 0.1
      - distance_to_previous:
        - norm: L1
        - coef: 0.1
      - abs_val:
        - variable: P_s
        - coef: 0.1

  model_parameters:
    - state/control variable:
      - lower bound
      - upper bound
      - constraint type: soft/hard
      - penalty coefficient: in case of soft constraint
      - penalty calculator: optional, default L1/L2
      - init_value: optional
      - steady_value: optional
    - constant parameter: 
      - value 
    - time varying parameter:
      - sampler: f(time_step)
        - parameters
    - noisy parameter:
      - sampler
        - parameters
    
estimator:
  - estimator type: StateFeedback/EKF(Extended Kalman Filter)/MHE(Moving Horizon Estimation)
  - parameters:
    - estimator related paramaters
